<?php
/**
 * Created by PhpStorm.
 * User: phw
 * Date: 18-3-12
 * Time: 上午10:51
 */

namespace app\controllers;

use app\models\OrderDetail;

class OrderDetailController extends BaseActiveController
{
    public $modelClass = 'app\models\OrderDetail';

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['create']);
        return $actions;
    }

    /**
     * @return array
     */
    public function actionCreate() {
        $model = new OrderDetail();
        $model->setAttributes($this->post);
        $model->user_id = $this->_userId;
        if ($model->save()) {
            return [
                'code' => 200,
                'message' => '保存成功'
            ];
        } elseif (!$model->hasErrors()) {
            return [
                'code' => 500,
                'message' => $model->errors];
        }
    }

}